name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  db-connection:
    description: 'db connection string'
    required: true
  source:
    description: 'source migrations'
    required: true
outputs:
  log:
    description: 'migration log'
runs:
  using: 'docker'
  image: 'docker://migrate/migrate'
  args:
    - ${{ source }}
    - ${{ db-connection }}
  entrypoint: 'entrypoint.sh'